### ISSUE TITLE
Install catalina aborted

### ISSUE THREAD

**Issue by Juliens67** [digitalec/thinkmac-t470#5] opened 2020-07-10 07:48 UTC
Hello,

Excuse me for my bad english (it's not my mother language).

My config : 
 - Bios version 1.64 (N1QET89W)
 - i5-7300U
 - Intel HD Graphics 620
 - Intel Dual Band Wireless-AC 8265
 - Inter Ethernet I219-LM
 - NVMe Toshiba

I put the same parameters in my bios than you.

I copied the EFI and Extras folders on my usb key.

1. Boot on usb key
2. Add option arg -v (verbose mode)
3. Choose : Boot macOS Install from my Niresh Catalina
4. Disk utility / Erase / APFS and GUID partition (for my entire nvme toshiba hdd)
5. Click on my HDD
6. Click on customize and tick all options
7. Continue / agree (install for 5 minutes)
==> automatic reboot

1. Boot on usb key
2. Add option arg -v (verbose mode)
3. Choose : Boot macOS Install from macOS HDD
   ( a lot of ACPI error on the screen )
   ( install for 15 minutes)
==> automatic reboot

1. Boot on usb key
2. Add option arg -v (verbose mode)
3. Choose : Boot macOS from macOS HDD
   ( a lot of ACPI error on the screen )
Install stopped on (1 on 1) almost at the end of progress bar

Could you please help me ?
what's going wrong ?

Thanks a lot in advance.

![hack1](https://user-images.githubusercontent.com/61978625/87130458-34cc3280-c293-11ea-937a-29c764f66140.jpg)
![hack2](https://user-images.githubusercontent.com/61978625/87130464-385fb980-c293-11ea-94ea-621311947cde.jpg)

**Comment by rguarascia** [comment] 2020-07-11 20:32
What model of ThinkPad are you using? T470? I didnt receive any ACPI errors on my T470 7th gen.

**Comment by digitalec** [comment] 2020-07-12 00:48
My config.plist won't work for the HD620. You'll have to grab that from [RehabMan's repo here](https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/config_HD615_620_630_640_650.plist).

Also, my DSDT won't work on your system so you can delete that and patch it using my notes in the README after install (certain things won't work until this is done).

**Comment by Juliens67** [comment] 2020-07-12 08:21
Yes, I use thinkpad T470. 

Digitalec, i’m going to download the config.plist for my HD620 from RehabMan’s repo (thanks for the link !)
Concerning the DSDT, which files I must to delete exactly in which directory ?

Thanks for your help. 
(I really would like use my T470 laptop as hackintosh instead of to buy a second-hand macbook)

**Comment by digitalec** [comment] 2020-07-12 15:36
@Juliens67 Sorry, disregard. I moved my patched DSDT to the Extras folder in a previous commit that I forgot about. You should be good with just that config.plist I linked.

**Comment by Juliens67** [comment] 2020-07-12 16:18
Thanks

I deleted the 2 DSDT files ans I use the config.plist for my HD620 from Rehabs repository. 

Now after the last reboot, it stopped here (see printscreen). ![image](https://user-images.githubusercontent.com/61978625/87251437-0fdee780-c46c-11ea-9780-1b20be223d6f.jpeg)

**Comment by digitalec** [comment] 2020-07-12 16:34
I had already moved DSDT.aml out of ACPI/patched in a previous commit so that isn't the issue. The ACPI error is regarding the battery.

Do you have dual batteries in your laptop?

If you have two batteries, did you modify the config.plist to rename the batteries to BATC instead of BAT0 and BAT1?

**Comment by rguarascia** [comment] 2020-07-12 17:10
@Juliens67 I have added my EFI to a fork of this repo. 

Make sure to generate new serials. 

https://github.com/rguarascia/thinkmac-t470

**Comment by Juliens67** [comment] 2020-07-12 20:06
@rguarascia I took your efi folder, I install Catalina from the usb disk and when i choose in clover : boot from hdd, it doesn't work and that pisses me off that I don't understand why.

I don't understand what I'm doing wrong.

![image](https://user-images.githubusercontent.com/61978625/87255500-9951e200-c48b-11ea-909b-e7285e0a97ff.jpeg)
![image](https://user-images.githubusercontent.com/61978625/87255514-ba1a3780-c48b-11ea-87ec-1a4b172188f5.jpeg)

**Comment by digitalec** [comment] 2020-07-12 20:22
Can you upload a zip of your EFI folder somewhere so I can take a look?

**Comment by Juliens67** [comment] 2020-07-12 20:42
I upload it tomorrow
(it's 11pm in France)

Thanks in advance.

**Comment by Juliens67** [comment] 2020-07-13 10:38
Hello,

You can download my EFI folder from here : https://github.com/Juliens67/jumac
My EFI is :
 - EFI from @digitalec 
 - config.plist from @rguarascia 

Thanks a lot for your help !

**Comment by digitalec** [comment] 2020-07-13 11:32
Let's start by removing the SMCBatteryManager.kext and seeing what happens.

In your images, there's a reference to failing to load AppleSmartBatteryManager due to it being a duplicate of org.rehabman.AppleSmartBatteryManager.

**Comment by Juliens67** [comment] 2020-07-13 14:03
I have to delete the file SMCBatteryManager.kext in the folder \EFI\CLOVER\kexts\Other\ ?
If yes, after that, I have to reinstall macOS or just boot from entry : Boot macOS from macOS HDD ?

I'll do that in 2 hours when I get home.
I'll inform you asap.

**Comment by digitalec** [comment] 2020-07-13 14:48
Just move the kext out of the kext/Other folder just in case it doesn't fix the issue. As long as it's not in the kext folder, it won't load.

I'm wondering if you're getting those errors because you don't have a patched DSDT yet and I believe that SSDT requires the changes.

You could always boot with only these KEXTs:

- Lilu
- WhateverGreen
- VoodooPS2Controller
- USBInjectAll

When I did my initial install, I used a stock config.plist from RehabMan and those 4 KEXTs. I could never get the onboard NIC card to work during the install so I used a USB network adapter.

**Comment by Juliens67** [comment] 2020-07-13 16:50
Firstly, I removed the file SMCBatteryManager.kext ==> same problem
Secondly, I rename the ACPI folder and I kept only the 4 kexts ==> I can configure Catalina ! :D

Now, I must to find what's working and what's not working...

Thanks a lot for your help !!!

**Comment by digitalec** [comment] 2020-07-14 04:13
I bet the `SSDT-BATC-T470.aml` file was the issue since removing `SMCBatteryManager.kext` had no affect. Once you patch your DSDT you can add that file back and it should work.

**Closed** 2020-07-14 04:13 UTC
